### ISSUE TITLE
stops working after a few seconds

### ISSUE THREAD

**Issue by 0mark** [Grumbel/udraw#2] opened 2013-08-29 14:30 UTC
It works great in all modes, but stops working after a few seconds. Pressing a Button does help, but again only a few seconds.

**Comment by TheSandBoxMKG** [comment] 2018-04-21 02:57
Have you checked if the player number LEDs were lit? The ones next to the start and select button.

**Comment by Grumbel** [comment] 2022-06-04 12:36
The controller will go into standby after 5min (LEDs go off), but will turn back on when you press a button. Pressing the touchpad isn't enough to wake it up again, but it is enough to keep it awake and prevent standby. 

If the controller loses contact with the USB receiver it will start blinking the LEDs. This might be a possible cause here, in case there is some interference (phones, WiFI, USB3.0 ports, etc).

Can't reproduce the issue, so I am closing it unless somebody can come up with a way to reproduce this.

**Closed by Grumbel** 2022-06-04 12:36 UTC
